CREATE TABLE USER_TABLE
(
    username VARCHAR2(50) NOT NULL PRIMARY KEY,
    email_address VARCHAR2(100),
    DOB DATE,
    ppassword VARCHAR2(20) NOT NULL,
    ddescription VARCHAR2(255)
);

DESCRIBE USER_TABLE ;
DROP TABLE USER_TABLE ;

CREATE TABLE USER_PHN_NO_TABLE
(
    username VARCHAR2(50) NOT NULL,
    phone_no VARCHAR2(100) NOT NULL,
    PRIMARY KEY(username, phone_no),
    CONSTRAINT FK_USER_PHN_NOusername FOREIGN KEY 
    (username) REFERENCES USER_TABLE (username) ON DELETE CASCADE
);

DESCRIBE USER_PHN_NO_TABLE ;
DROP TABLE USER_PHN_NO_TABLE ;

CREATE TABLE CUSTOMER_TABLE
(
    username VARCHAR2(50) NOT NULL PRIMARY KEY,
    street VARCHAR2(100) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    sstate VARCHAR2(100) NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    CONSTRAINT FK_CUSTOMERusername FOREIGN KEY 
    (username) REFERENCES USER_TABLE (username) ON DELETE CASCADE
);

DESCRIBE CUSTOMER_TABLE ;
DROP TABLE CUSTOMER_TABLE ;

CREATE TABLE ADMINISTRATOR_TABLE
(
    username VARCHAR2(50) NOT NULL PRIMARY KEY,
    CONSTRAINT FK_ADMINISTRATORusername FOREIGN KEY 
    (username) REFERENCES USER_TABLE (username) ON DELETE CASCADE
);

DESCRIBE ADMINISTRATOR_TABLE ;
DROP TABLE ADMINISTRATOR_TABLE ;

CREATE TABLE ORDERS_TABLE
(
    order_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    invoice_no NUMBER(10, 0) NOT NULL UNIQUE,
    order_date TIMESTAMP DEFAULT CURRENT_DATE NOT NULL,
    order_status VARCHAR2(100) NOT NULL,
    username VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ORDERSusername FOREIGN KEY 
    (username) REFERENCES CUSTOMER_TABLE (username) ON DELETE CASCADE
);

DESCRIBE ORDERS_TABLE ;
DROP TABLE ORDERS_TABLE ;

CREATE TABLE TRACKING_DETAILS_TABLE
(
    tracking_id NUMBER(10, 0) NOT NULL,
    order_id NUMBER(10, 0) NOT NULL,
    courier_name VARCHAR2(100) NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_DATE NOT NULL,
    ddescription VARCHAR2(100) NOT NULL,
    PRIMARY KEY(tracking_id, order_id),
    CONSTRAINT FK_TRACKING_DETAILSorder_id FOREIGN KEY 
    (order_id) REFERENCES ORDERS_TABLE (order_id) ON DELETE CASCADE
);

DESCRIBE TRACKING_DETAILS_TABLE ;
DROP TABLE TRACKING_DETAILS_TABLE ;

CREATE TABLE ORDER_DETAILS_TABLE
(
    order_details_id NUMBER(10, 0) NOT NULL UNIQUE,
    order_id NUMBER(10, 0) NOT NULL,
    discount DECIMAL(5, 2) DEFAULT 0 CHECK (discount >= 0 AND discount <= 100) NOT NULL,
    amount_to_pay NUMBER(10, 3) DEFAULT 0 NOT NULL,
    PRIMARY KEY(order_details_id, order_id),
    CONSTRAINT FK_ORDER_DETAILS_TABLEorder_id FOREIGN KEY 
    (order_id) REFERENCES ORDERS_TABLE (order_id) ON DELETE CASCADE
);

DESCRIBE ORDER_DETAILS_TABLE ;
DROP TABLE ORDER_DETAILS_TABLE ;

CREATE TABLE AUTHOR_TABLE
(
    author_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    author_name VARCHAR2(50) NOT NULL,
    email_address VARCHAR2(100) NOT NULL
);

DESCRIBE AUTHOR_TABLE ; 
DROP TABLE AUTHOR_TABLE ;

CREATE TABLE PUBLISHER_TABLE
(
    publisher_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    publisher_name VARCHAR2(100) NOT NULL,
    email_address VARCHAR2(100) NOT NULL,
    website VARCHAR2(100) NOT NULL
);

DESCRIBE PUBLISHER_TABLE ;
DROP TABLE PUBLISHER_TABLE ;

CREATE TABLE BOOK_TABLE
(
    book_ISBN NUMBER(10, 0) NOT NULL PRIMARY KEY,
    book_title VARCHAR2(255),
    eedition NUMBER(2, 0),
    price NUMBER(7, 3) NOT NULL,
    EOQ NUMBER(7, 3),
    author_id NUMBER(10, 0) NOT NULL,
    publisher_id NUMBER(10, 0) NOT NULL,
    release_date DATE,
    page_count NUMBER(4, 0),
    dimensions VARCHAR2(50),
    quantity_in_stock NUMBER(6, 0) DEFAULT 0 CHECK (quantity_in_stock >= 0) NOT NULL,
    CONSTRAINT FK_BOOKauthor_id FOREIGN KEY 
    (author_id) REFERENCES AUTHOR_TABLE (author_id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKpublisher_id FOREIGN KEY 
    (publisher_id) REFERENCES PUBLISHER_TABLE (publisher_id) ON DELETE CASCADE
);

DESCRIBE BOOK_TABLE ;
DROP TABLE BOOK_TABLE ;

CREATE TABLE BOOK_INSTANCE_TABLE
(
    copy_instance NUMBER(10, 0) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    quantity NUMBER(5, 0) NOT NULL,
    order_details_id NUMBER(10, 0) NOT NULL,
    order_id NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(copy_instance, book_ISBN),
    CONSTRAINT FK_BOOK_INSTANCEbook_ISBN FOREIGN KEY 
    (book_ISBN) REFERENCES BOOK_TABLE (book_ISBN) ON DELETE CASCADE, 
    CONSTRAINT FK_BOOK_INSTANCEorder_details_id FOREIGN KEY 
    (order_details_id) REFERENCES ORDER_DETAILS_TABLE (order_details_id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOK_INSTANCEorder_id FOREIGN KEY 
    (order_id) REFERENCES ORDERS_TABLE (order_id) ON DELETE CASCADE
);

DESCRIBE BOOK_INSTANCE_TABLE ; 
DROP TABLE BOOK_INSTANCE_TABLE ;

CREATE TABLE CATEGORY_TABLE
(
    category_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL,
    parent_id NUMBER(10, 0),
    CONSTRAINT FK_CATEGORYparent_id FOREIGN KEY 
    (parent_id) REFERENCES CATEGORY_TABLE (category_id) ON DELETE SET NULL
);

DESCRIBE CATEGORY_TABLE ;
DROP TABLE CATEGORY_TABLE ;

CREATE TABLE LANGUAGE_TABLE
(
    language_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    language_name VARCHAR2(50) NOT NULL,
    ddescription VARCHAR2(255)
);

DESCRIBE LANGUAGE_TABLE ;
DROP TABLE LANGUAGE_TABLE ;

CREATE TABLE BINDING_TABLE
(
    binding_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    binding_type VARCHAR2(50) NOT NULL,
    ddescription VARCHAR2(255)
);

DESCRIBE BINDING_TABLE ;
DROP TABLE BINDING_TABLE ;

CREATE TABLE BOOK_CATEGORY_TABLE 
(
    category_id NUMBER(10, 0) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(category_id, book_ISBN),
    CONSTRAINT FK_BOOK_CATEGORY_TABLEcategory_id FOREIGN KEY 
    (category_id) REFERENCES CATEGORY_TABLE (category_id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOK_CATEGORY_TABLEbook_ISBN FOREIGN KEY 
    (book_ISBN) REFERENCES BOOK_TABLE (book_ISBN) ON DELETE CASCADE
);

DESCRIBE BOOK_CATEGORY_TABLE ;
DROP TABLE BOOK_CATEGORY_TABLE ;

CREATE TABLE BOOK_LANGUAGE_TABLE
(
    language_id NUMBER(10, 0) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(language_id, book_ISBN),
    CONSTRAINT FK_BOOK_LANGUAGE_TABLElanguage_id FOREIGN KEY 
    (language_id) REFERENCES LANGUAGE_TABLE (language_id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOK_LANGUAGE_TABLEbook_ISBN FOREIGN KEY 
    (book_ISBN) REFERENCES BOOK_TABLE (book_ISBN) ON DELETE CASCADE
);

DESCRIBE BOOK_LANGUAGE_TABLE ;
DROP TABLE BOOK_LANGUAGE_TABLE ;

CREATE TABLE BOOK_BINDING_TABLE
(
    binding_id NUMBER(10, 0) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(binding_id, book_ISBN),
    CONSTRAINT FK_BOOK_BINDING_TABLEbinding_id FOREIGN KEY 
    (binding_id) REFERENCES BINDING_TABLE (binding_id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOK_BINDING_TABLEbook_ISBN FOREIGN KEY 
    (book_ISBN) REFERENCES BOOK_TABLE (book_ISBN) ON DELETE CASCADE
);

DESCRIBE BOOK_BINDING_TABLE ;
DROP TABLE BOOK_BINDING_TABLE ;

CREATE TABLE SUPPLIER_TABLE
(
    supplier_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    email_address VARCHAR2(100) NOT NULL,
    supplier_name VARCHAR2(100) NOT NULL,
    contact_no VARCHAR2(100) NOT NULL,
    street VARCHAR2(100) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    sstate VARCHAR2(100) NOT NULL
);

DESCRIBE SUPPLIER_TABLE ;
DROP TABLE SUPPLIER_TABLE ;

CREATE TABLE SUPPLIES_TO_TABLE
(
    publisher_id NUMBER(10, 0) NOT NULL,
    supplier_id NUMBER(10, 0) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL UNIQUE,
    amount NUMBER(6, 0) NOT NULL CHECK (amount >= 0),
    PRIMARY KEY(publisher_id, supplier_id),
    CONSTRAINT FK_SUPPLIES_TO_TABLEpublisher_id FOREIGN KEY 
    (publisher_id) REFERENCES PUBLISHER_TABLE (publisher_id) ON DELETE CASCADE,
    CONSTRAINT FK_SUPPLIES_TO_TABLEsupplier_id FOREIGN KEY 
    (supplier_id) REFERENCES SUPPLIER_TABLE (supplier_id) ON DELETE CASCADE
);

DESCRIBE SUPPLIES_TO_TABLE ;
DROP TABLE SUPPLIES_TO_TABLE ;

CREATE TABLE WAREHOUSE_TABLE
(
    warehouse_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    warehouse_name VARCHAR2(100) NOT NULL,
    street VARCHAR2(100) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    sstate VARCHAR2(100) NOT NULL,
    manager_contact VARCHAR2(100) NOT NULL
);

DESCRIBE WAREHOUSE_TABLE ;
DROP TABLE WAREHOUSE_TABLE ;

CREATE TABLE PROVIDES_BOOKS_TABLE
(
    supplier_id NUMBER(10, 0) NOT NULL,
    warehouse_id NUMBER(10, 0) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL UNIQUE,
    amount NUMBER(6, 0) NOT NULL CHECK (amount >= 0),
    PRIMARY KEY(supplier_id, warehouse_id),
    CONSTRAINT FK_PROVIDES_BOOKS_TABLEsupplier_id FOREIGN KEY 
    (supplier_id) REFERENCES SUPPLIER_TABLE (supplier_id) ON DELETE CASCADE,
    CONSTRAINT FK_PROVIDES_BOOKS_TABLEwarehouse_id FOREIGN KEY 
    (warehouse_id) REFERENCES WAREHOUSE_TABLE (warehouse_id) ON DELETE CASCADE
);

DESCRIBE PROVIDES_BOOKS_TABLE ;
DROP TABLE PROVIDES_BOOKS_TABLE ;

CREATE TABLE BOOKS_WITH_SUPPLIERS_TABLE
(
    track_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    book_ISBN NUMBER(10, 0) NOT NULL UNIQUE,
    quantity NUMBER(6, 0) DEFAULT 0 CHECK (quantity >= 0) NOT NULL
);

DESCRIBE BOOKS_WITH_SUPPLIERS_TABLE ;
DROP TABLE BOOKS_WITH_SUPPLIERS_TABLE ;

CREATE TABLE HAVE_BOOKS_TABLE
(
    supplier_id NUMBER(10, 0) NOT NULL,
    track_id NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(supplier_id, track_id),
    CONSTRAINT FK_HAVE_BOOKS_TABLEsupplier_id FOREIGN KEY 
    (supplier_id) REFERENCES SUPPLIER_TABLE (supplier_id) ON DELETE CASCADE,
    CONSTRAINT FK_HAVE_BOOKS_TABLEtrack_id FOREIGN KEY 
    (track_id) REFERENCES BOOKS_WITH_SUPPLIERS_TABLE (track_id) ON DELETE CASCADE
);

DESCRIBE HAVE_BOOKS_TABLE ;
DROP TABLE HAVE_BOOKS_TABLE ;

CREATE TABLE BOOKS_IN_WAREHOUSE_TABLE
(
    track_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    book_ISBN NUMBER(10, 0) NOT NULL UNIQUE,
    quantity NUMBER(6, 0) DEFAULT 0 CHECK (quantity >= 0) NOT NULL
);

DESCRIBE BOOKS_IN_WAREHOUSE_TABLE ;
DROP TABLE BOOKS_IN_WAREHOUSE_TABLE ;

CREATE TABLE CONTAINS_BOOKS_TABLE
(
    warehouse_id NUMBER(10, 0) NOT NULL,
    track_id NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(warehouse_id, track_id),
    CONSTRAINT FK_CONTAINS_BOOKS_TABLEwarehouse_id FOREIGN KEY 
    (warehouse_id) REFERENCES WAREHOUSE_TABLE (warehouse_id) ON DELETE CASCADE,
    CONSTRAINT FK_CONTAINS_BOOKS_TABLEtrack_id FOREIGN KEY 
    (track_id) REFERENCES BOOKS_IN_WAREHOUSE_TABLE (track_id) ON DELETE CASCADE
);

DESCRIBE CONTAINS_BOOKS_TABLE ;
DROP TABLE CONTAINS_BOOKS_TABLE ;

CREATE TABLE USER_INTERACTION_TABLE
(
    username VARCHAR2(50) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    rating NUMBER(1, 0),
    upvote CHAR(1),
    downvote CHAR(1),
    PRIMARY KEY(username, book_ISBN),
    CONSTRAINT FK_USER_INTERACTION_TABLEusername FOREIGN KEY 
    (username) REFERENCES CUSTOMER_TABLE (username) ON DELETE CASCADE,
    CONSTRAINT FK_USER_INTERACTION_TABLEbook_ISBN FOREIGN KEY 
    (book_ISBN) REFERENCES BOOK_TABLE (book_ISBN) ON DELETE CASCADE
);

DESCRIBE USER_INTERACTION_TABLE ;
DROP TABLE USER_INTERACTION_TABLE ;

CREATE TABLE FAVOURITES_TABLE
(
    favourite_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    reason VARCHAR2(255)
);

DESCRIBE FAVOURITES_TABLE ;
DROP TABLE FAVOURITES_TABLE ;

CREATE TABLE USER_FAVOURITE_TABLE
(
    username VARCHAR2(50) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    favourite_id NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(username, book_ISBN, favourite_id),
    CONSTRAINT FK_USER_FAVOURITE_TABLEusernamebook_ISBN FOREIGN KEY 
    (username, book_ISBN) REFERENCES USER_INTERACTION_TABLE (username, book_ISBN) ON DELETE CASCADE,
    CONSTRAINT FK_USER_FAVOURITE_TABLEfavourite_id FOREIGN KEY 
    (favourite_id) REFERENCES FAVOURITES_TABLE (favourite_id) ON DELETE CASCADE
);

DESCRIBE USER_FAVOURITE_TABLE ;
DROP TABLE USER_FAVOURITE_TABLE ;

CREATE TABLE COMMENTS_TABLE
(
    comment_id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    ccomment VARCHAR2(255) NOT NULL
);

DESCRIBE COMMENTS_TABLE ;
DROP TABLE COMMENTS_TABLE ;

CREATE TABLE USER_COMMENT_TABLE
(
    username VARCHAR2(50) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    comment_id NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(username, book_ISBN, comment_id),
    CONSTRAINT FK_USER_COMMENT_TABLEusernamebook_ISBN FOREIGN KEY 
    (username, book_ISBN) REFERENCES USER_INTERACTION_TABLE (username, book_ISBN) ON DELETE CASCADE,
    CONSTRAINT FK_USER_COMMENT_TABLEcomment_id FOREIGN KEY 
    (comment_id) REFERENCES COMMENTS_TABLE (comment_id) ON DELETE CASCADE
);

DESCRIBE USER_COMMENT_TABLE ;
DROP TABLE USER_COMMENT_TABLE ;

CREATE TABLE WISHLIST_TABLE
(
    wish_id NUMBER(10, 0) NOT NULL PRIMARY KEY
);

DESCRIBE WISHLIST_TABLE ;
DROP TABLE WISHLIST_TABLE ;

CREATE TABLE USER_WISHLIST_TABLE
(
    username VARCHAR2(50) NOT NULL,
    book_ISBN NUMBER(10, 0) NOT NULL,
    wish_id NUMBER(10, 0) NOT NULL,
    PRIMARY KEY(username, book_ISBN, wish_id),
    CONSTRAINT FK_USER_WISHLIST_TABLEusernamebook_ISBN FOREIGN KEY 
    (username, book_ISBN) REFERENCES USER_INTERACTION_TABLE (username, book_ISBN) ON DELETE CASCADE,
    CONSTRAINT FK_USER_WISHLIST_TABLEwish_id FOREIGN KEY 
    (wish_id) REFERENCES WISHLIST_TABLE (wish_id) ON DELETE CASCADE
);

DESCRIBE USER_WISHLIST_TABLE ;
DROP TABLE USER_WISHLIST_TABLE ;